### ISSUE TITLE
microOS: Vagrant boxes fail to start

### ISSUE THREAD

**Issue by votdev** [aquarist-labs/aquarium#76] opened 2021-02-09 09:55 UTC
**Describe the bug**
After building the Vabgrant box according to https://github.com/aquarist-labs/aquarium/pull/38 deploying the Vagrant cluster via `vagrant up` is not possible because booting the system fails.

![Bildschirmfoto von 2021-02-09 10-10-31](https://user-images.githubusercontent.com/1897962/107346693-47c31180-6ac5-11eb-8538-7dc836c08819.png)

**Comment by asettle** [comment] 2021-02-25 15:44
@l-mb did you experience this issue when updating the docs?

**Comment by l-mb** [comment] 2021-03-02 12:12
@asettle No, I also couldn't reproduce on Tumbleweed.

**Comment by jecluis** [comment] 2021-03-02 14:42
@votdev closing this. Let us know if you are able to reproduce this.

**Closed by jecluis** 2021-03-02 14:42 UTC
Labels: Required, bug, documentation
